/* DSblock model generated by Dymola from Modelica model HydrogenComponents.Examples.ExElOnly
 Dymola Version 2018 (32-bit), 2017-04-10 translated this at Fri Mar 05 17:18:12 2021

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    3
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    19
#define NP_    2
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -636883128
#define NHash2_ 2105819532
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  1
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    12
#define SizePre_ 0
#define SizeEq_ 1
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0
};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0
};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="HydrogenComponents.Examples.ExElOnly";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[6]={1 , 3 , 1 , 2 , 3 , 0};
DYMOLA_STATIC int QJacobianGC_[4]={
0 , 1 , 1 , 0};
DYMOLA_STATIC double QJacobianCD_[4]={0  , 44 , 55 , 66};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,3) = 236483;
DYNX(W_,5) = 2;
DYNX(W_,11) = 1.225486780822983;
DYNX(W_,8) = 50000.0;
DYNX(W_,10) = 1;
DYNX(W_,12) = 1.4339777157327116;
DYNX(W_,1) = 0;
DYNX(W_,4) = 285830;
DYNX(W_,7) = 298.15;
DYNX(W_,6) = 298.15;
DYNX(W_,18) = 0.05;
DYNX(W_,2) = 0.0;
DYNX(W_,9) = 50000.0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(F_,0) = 0.02;
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(F_,0) = 0.02;
 /* Linear system of equations to solve. */
DYNX(W_,15) = RememberSimple_(DYNX(W_,15), 0);
SolveScalarLinearParametric( -DYNX(DP_,0)," -E.A",  -DYNX(X_,0)," -PI.i", 
  DYNX(W_,15),"E.i");
 /* End of Equation Block */ 

DYNX(W_,13) = divmacro(4957.912378739999*asinh(10.0*DYNX(W_,15)),
  "4957.912378739999*asinh(10.0*E.i)",DYNX(DP_,1)*96485.33289,"E.alpha_m*96485.33289");
DYNX(W_,14) = 0.0005*DYNX(X_,0);
DYNX(W_,0) = 1.4339777157327116+DYNX(W_,13)+DYNX(W_,14);
DYNX(F_,1) = DYNX(W_,0)*DYNX(X_,0);
DYNX(F_,2) = 5.1821347869529016E-006*DYNX(X_,0);

AcceptedSection1

AcceptedSection2
DYNX(W_,16) = DYNX(W_,0)*DYNX(X_,0);
DYNX(W_,17) = IF Equal(DYNX(W_,16), 0, 0) THEN 0 ELSE divmacro(DYNX(F_,2),
  "der(HS.n)",DYNX(W_,16),"E.P_el");

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("PI.p.v", "Potential at the pin [V]", 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("PI.p.i", "Current flowing into the pin [A]", "PI.i", -1, 1, 0, 132)
DeclareVariable("PI.n.v", "Potential at the pin [V]", 0, 0.0,0.0,0.0,0,521)
DeclareAlias2("PI.n.i", "Current flowing into the pin [A]", "PI.i", 1, 1, 0, 132)
DeclareState("PI.i", "[A]", 0, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("PI.der(i)", "[A/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("PI.v", "[V]", "PI.p.v", 1, 5, 0, 0)
DeclareState("PI.InputPower", "[J]", 1, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("PI.der(InputPower)", "[W]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("E.p.v", "Potential at the pin [V]", "PI.p.v", 1, 5, 0, 4)
DeclareAlias2("E.p.i", "Current flowing into the pin [A]", "PI.i", 1, 1, 0, 132)
DeclareVariable("E.n.v", "Potential at the pin [V]", 0.0, 0.0,0.0,0.0,0,521)
DeclareAlias2("E.n.i", "Current flowing into the pin [A]", "PI.i", -1, 1, 0, 132)
DeclareAlias2("E.h.N", "molar flowrate of Hydrogen [mol/s]", "HS.der(n)", -1, 6,\
 2, 132)
DeclareParameter("E.A", "Area of exchange-membrane [m2]", 0, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("E.N_H2", "[mol/s]", "HS.der(n)", 1, 6, 2, 0)
DeclareVariable("E.G", "freie Gische Energie bei T=298,15K und P=1atm [J/mol]", 236483,\
 0.0,0.0,20000.0,0,513)
DeclareVariable("E.H", "Reaktionsenthalpie bei T=298,15K und P=1atm [J/mol]", 285830,\
 0.0,0.0,20000.0,0,513)
DeclareVariable("E.z", "Anzahl der ausgetauschten Elektronen pro Elementarreaktion",\
 2, 0.0,0.0,0.0,0,513)
DeclareVariable("E.T_0", "standard temperature [K|degC]", 298.15, 0.0,1E+100,\
300.0,0,513)
DeclareVariable("E.T", "temperature of incomming Water [K|degC]", 298.15, 0.0,\
1E+100,300.0,0,513)
DeclareVariable("E.p_H2", "partial pressure H2 [Pa|bar]", 50000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("E.p_O2", "partial pressure O2 [Pa|bar]", 50000.0, 0.0,0.0,0.0,0,513)
DeclareVariable("E.a_H2O", "water activity (equals 1 for liquid water) [PA^1.5]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("E.V_cell", "produced/needed Cell-Voltage [V]", "PI.p.v", 1, 5, 0,\
 0)
DeclareVariable("E.V_rev_0", "reversible Cell-Voltage at T=298,15K and P=1atm [V]",\
 1.225486780822983, 0.0,0.0,0.0,0,513)
DeclareVariable("E.V_rev", "reversible Cell-Voltage [V]", 1.4339777157327116, \
0.0,0.0,0.0,0,513)
DeclareVariable("E.V_act", "Voltage-losse due to activation processes [V]", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareVariable("E.V_ohm", "ohmic Voltage-losses [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("E.I", "[A]", "PI.i", 1, 1, 0, 0)
DeclareVariable("E.i", "[A/m2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.P_el", "electrical power in/output [W]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.eff", "[1]", 0.0, 0.0,1E+100,0.0,0,512)
DeclareParameter("E.alpha_m", "[1]", 1, 0.5, 0.0,0.0,0.0,0,560)
DeclareVariable("E.i_0", "[A/m2]", 0.05, 0.0,0.0,0.0,0,513)
DeclareAlias2("HS.h.N", "molar flowrate of Hydrogen [mol/s]", "HS.der(n)", 1, 6,\
 2, 132)
DeclareAlias2("HS.N_H2", "[mol/s]", "HS.der(n)", 1, 6, 2, 0)
DeclareState("HS.n", "[mol]", 2, 0, 0.0,1E+100,0.0,0,560)
DeclareDerivative("HS.der(n)", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,15), 0.0, 0);
EndEqBlock
EndDataBlock
