/* DSblock model generated by Dymola from Modelica model HydrogenComponents.Examples.ExElOnly
 Dymola Version 2018 (32-bit), 2017-04-10 translated this at Tue Apr 06 19:50:54 2021

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    2
#define NX2_   1
#define NU_    0
#define NY_    0
#define NW_    41
#define NP_    8
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -573119313
#define NHash2_ -1429176827
#define NHash3_ 0
#define NI_    0
#define NRelF_ 2
#define NRel_  3
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    16
#define SizePre_ 0
#define SizeEq_ 1
#define SizeDelay_ 0
#define QNLmax_ 1
#define MAXAux 1
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 45
#define NGlobalHelpI_ 23
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0
};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0
};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="HydrogenComponents.Examples.ExElOnly";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[5]={1 , 2 , 1 , 2 , 0};
DYMOLA_STATIC int QJacobianGC_[3]={
0 , 1 , 0};
DYMOLA_STATIC double QJacobianCD_[3]={0  , 44 , 55};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,11) = 2.02;
DYNX(W_,13) = 16;
DYNX(W_,14) = 18.02;
DYNX(W_,15) = 1004;
DYNX(W_,20) = 298.15;
DYNX(W_,21) = 103105;
DYNX(W_,36) = 2.02;
DYNX(W_,38) = 16;
DYNX(W_,40) = 18.02;
DYNX(W_,4) = 20000.0;
DYNX(W_,16) = 236483;
DYNX(W_,19) = 2;
DYNX(W_,26) = 1.225486780822983;
DYNX(W_,23) = 1;
DYNX(W_,9) = 3.314735808515448E-011;
DYNX(W_,17) = 285830;
DYNX(W_,25) = 1.481209586154748;
DYNX(W_,18) = 285830.0;
DYNX(W_,7) = 0.002;
DYNX(W_,22) = 298.15;
DYNX(W_,3) = 0.00218;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(DYNhelp,0) = sqrtGuarded(9.698850686193686E-006*DYNX(DP_,6),
  "9.698850686193686E-006*E.p_O2");
DYNX(DYNhelp,1) = logGuarded(9.698850686193686E-006*DYNX(DP_,5)*DYNX(DYNhelp,0),
  "9.698850686193686E-006*(E.p_H2*sqrt(9.698850686193686E-006*E.p_O2))");
DYNX(W_,27) = 1.225359280822983+0.01284628510426648*DYNX(DYNhelp,1);
DYNX(W_,5) = 0.9341910070486358*(0.005139*DYNX(DP_,3)-0.00326);
DYNX(W_,6) = divmacro(DYNX(DP_,2),"E.delta",DYNX(W_,5),"E.sigma_pem");
DYNX(W_,8) = (-2.04)*DYNX(DP_,4)-0.0028*sqr(DYNX(DP_,4))+1.5897358*DYNX(DP_,4)+
  0.6949522052658058*DYNX(DP_,4)+0.001043*powmacro2(DYNX(DP_,4),"E.m",3,"3")-
  0.026668026749999994*sqr(DYNX(DP_,4));
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(F_,0) = 100;
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(F_,0) = 100;

if (Init_ || DYNTime==InitTime) {
DYNX(Aux_,0) = Less(DYNX(W_,32),"E.i", 20000.0,"20000.0", 0);}
MixedSystemOfEquations(6, DYNX(DYNhelp,2))

  { /* Non-linear system of equations to solve. */
  /* Tag: simulation.nonlinear[1] */
  /* Introducing 10 common subexpressions and reusing 1 variables totally
     used in 2 expressions */
  /* Of the common subexpressions 10 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"E.i"};
  const double nominal_[]={1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 1, 1, 
    DYNX(DYNhelp,8), 35, DYNX(did_->helpvari_vec,0), 23);
  SetInitVector(x__, 1, DYNX(W_,32), Remember_(DYNX(W_,32), 0));
  Residues;
    DYNX(W_,31) = DYNX(DP_,1)*DYNX(W_,32);
    DYNX(W_,29) = DYNX(W_,31)*(0.002+DYNX(W_,6));
    DYNX(DYNhelp,43) = Equal(DYNX(W_,32), 0, 1);
    DYNX(W_,28) = IF DYNX(DYNhelp,43) THEN 0 ELSE divmacro(2478.9561893699997*
      logGuarded(458.7155963302752*DYNX(W_,32),"458.7155963302752*E.i"),
      "2478.9561893699997*log(458.7155963302752*E.i)",96485.33289*DYNX(DP_,0)*2,
      "96485.33289*(E.alpha_m*2)");
    DYNX(W_,30) = IF DYNX(Aux_,0) THEN 0.01284628510426648*logGuarded(divmacro(
      20000.0,"20000.0",20000.0-DYNX(W_,32),"20000.0-E.i"),"20000.0/(20000.0-E.i)")
       ELSE 0;
    DYNX(W_,24) = DYNX(W_,27)+DYNX(W_,28)+DYNX(W_,29)+DYNX(W_,30);
  SetVector(residue__, 1, DYNX(X_,0)-DYNX(W_,24)*DYNX(W_,31));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  SetMatrixLeading(Jacobian__, 1, 1, 1,  -((DYNX(W_,24)+DYNX(W_,29))*DYNX(DP_,1)
    +DYNX(W_,31)*(IF DYNX(DYNhelp,43) THEN 0.0 ELSE divmacro(divmacro(
    1137135.8666834862,"1137135.8666834862",458.7155963302752*DYNX(W_,32),
    "458.7155963302752*E.i"),"1137135.8666834862/(458.7155963302752*E.i)",
    96485.33289*DYNX(DP_,0)*2,"96485.33289*(E.alpha_m*2)"))+DYNX(W_,31)*(IF 
    DYNX(Aux_,0) THEN  -divmacro((-0.01284628510426648)*(20000.0-DYNX(W_,32)),
    "(-0.01284628510426648)*(20000.0-E.i)",sqr(20000.0-DYNX(W_,32)),
    "(20000.0-E.i)^2") ELSE 0.0)));

  SolveNonLinearSystemOfEquationsMixed(Jacobian__, residue__, x__,"Tag: simulation.nonlinear[1]");
  DYNX(W_,32) = GetVector(x__, 1);
  EndNonLinearSystemOfEquations(residue__, x__);
   /* End of Non-Linear Equation Block */ }




  MixedModeStartBoolean
  UpdateVariableNamed(DYNX(Aux_,0),"discreteexpr_0.", Less(DYNX(W_,32),"E.i", 
    20000.0,"20000.0", 0));
  MixedModeInit(1, DYNX(DYNhelp,44))
  ThetaMixedCross(0,0)
  MixedModeEndBoolean
  UpdateReal(DYNX(W_,30), 1)
  UpdateReal(DYNX(W_,29), 2)
  UpdateReal(DYNX(W_,24), 3)
  UpdateReal(DYNX(W_,28), 4)
  UpdateReal(DYNX(W_,32), 5)
  UpdateReal(DYNX(W_,31), 6)
EndMixedSystemOfEquations

DYNX(W_,10) = 5.1821347869529016E-006*DYNX(W_,31);
DYNX(W_,1) = 2.02*DYNX(W_,10);
DYNX(F_,1) = (-0.49504950495049505)*DYNX(W_,1);

AcceptedSection1

AcceptedSection2
DYNX(W_,12) = 0.5*DYNX(W_,10);
DYNX(W_,0) = 16*DYNX(W_,12);
DYNX(W_,2) = 18.02*DYNX(W_,10);
DYNX(W_,33) = DYNX(W_,24)*DYNX(W_,31);
DYNX(W_,34) = 18092.079999999998*DYNX(W_,10)*(DYNX(DP_,7)-298.15)-
  1.4812095861547478*DYNX(W_,31)+DYNX(W_,33);
DYNX(W_,35) = IF Equal(DYNX(W_,33), 0, 2) THEN 0 ELSE divmacro(285830.0*
  DYNX(W_,10),"285830.0*E.n_H2",DYNX(W_,33),"E.P_el");
DYNX(W_,37) = (-0.0625)*DYNX(W_,0);
DYNX(W_,39) = (-0.05549389567147614)*DYNX(W_,2);

DefaultSection
InitialSection
DYNX(Aux_,0) = DYNX(W_,32) < 20000.0;
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareState("PI.PowerOutput", "[W]", 0, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("PI.der(PowerOutput)", "[W/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.O2_Output.m_flow", "mass flow rate of sub-component [kg/s]", \
0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("E.O2_Output.p", "partial pressure of sub-component [Pa|bar]", \
"E.p_O2", 1, 7, 6, 4)
DeclareVariable("E.H2_Output.m_flow", "mass flow rate of sub-component [kg/s]", \
0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("E.H2_Output.p", "partial pressure of sub-component [Pa|bar]", \
"E.p_H2", 1, 7, 5, 4)
DeclareVariable("E.H2O_Input.m_flow", "mass flow rate of sub-component [kg/s]", \
0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("E.H2O_Input.p", "partial pressure of sub-component [Pa|bar]", \
"E.p_O2", 1, 7, 6, 4)
DeclareAlias2("E.PowerInput", "Input power for the elektrolyser [W]", \
"PI.PowerOutput", 1, 1, 0, 0)
DeclareParameter("E.alpha_m", "f\303\274r \303\234berspannung [1]", 0, 0.5, \
0.0,0.0,0.0,0,560)
DeclareParameter("E.A", "active area [m2]", 1, 0.0025, 0.0,0.0,0.0,0,560)
DeclareVariable("E.i_0", "hat mit Material der Membran zu tun [A/m2]", 0.00218, \
0.0,0.0,0.0,0,513)
DeclareVariable("E.i_max", "maximal stromdichte [A/m2]", 20000.0, 0.0,0.0,0.0,0,513)
DeclareParameter("E.delta", "membran thickness [m]", 2, 0.000175, 0.0,0.0,0.0,0,560)
DeclareVariable("E.sigma_pem", "conductivity of membran [S/m]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareParameter("E.lambda", "water content of membran (dry: ~0.5; water saturated gas: ~13; liquid water: ~22)",\
 3, 22, 0.0,0.0,0.0,0,560)
DeclareVariable("E.R_mem", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("E.R_ele", "", 0.002, 0.0,0.0,0.0,0,513)
DeclareParameter("E.m", "molar Concentration of the electrolyt-solution", 4, 0.2,\
 0.0,0.0,0.0,0,560)
DeclareVariable("E.sigma_alk", "conductivity of elektrolyte [S/m]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("E.sigma_so", "conductivity of elektrolyte [S/m]", \
3.314735808515448E-011, 0.0,0.0,0.0,0,513)
DeclareVariable("E.n_H2", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.M_H2", "[kg/mol]", 2.02, 0.0,1E+100,0.0,0,513)
DeclareParameter("E.p_H2", "partial pressure H2 [Pa|bar]", 5, 400000, 0.0,1E+100,\
100000.0,0,560)
DeclareVariable("E.n_O2", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.M_O2", "[kg/mol]", 16, 0.0,1E+100,0.0,0,513)
DeclareParameter("E.p_O2", "partial pressure O2 [Pa|bar]", 6, 400000, 0.0,1E+100,\
100000.0,0,560)
DeclareAlias2("E.n_H2O", "[mol/s]", "E.n_H2", 1, 5, 10, 0)
DeclareVariable("E.M_H2O", "[kg/mol]", 18.02, 0.0,1E+100,0.0,0,513)
DeclareAlias2("E.p_H2O", "partial pressure H2O [Pa|bar]", "E.p_O2", 1, 7, 6, 0)
DeclareParameter("E.T_H2O", "temperature of incomming Water [K|degC]", 7, 298.15,\
 0.0,1E+100,300.0,0,560)
DeclareVariable("E.cp_H2O", "[J/(kg.K)]", 1004, 0.0,0.0,0.0,0,513)
DeclareVariable("E.G_r_0", "free gibbs reaktion energy at T=298,15K and P=1atm [J/mol]",\
 236483, 0.0,0.0,20000.0,0,513)
DeclareVariable("E.H_r", "reaktion enthalpy [J/mol]", 285830, 0.0,0.0,20000.0,0,513)
DeclareVariable("E.H_r_0", "reaktion enthalpy at T=298,15K and P=1atm [J/mol]", \
285830.0, 0.0,0.0,20000.0,0,513)
DeclareVariable("E.z", "nuber of exchanged elektrons per elementary reaktion", 2,\
 0.0,0.0,0.0,0,513)
DeclareVariable("E.T_0", "standard temperature [K|degC]", 298.15, 0.0,1E+100,\
300.0,0,513)
DeclareVariable("E.p_0", "standard pressure [Pa|bar]", 103105, 0.0,0.0,0.0,0,513)
DeclareVariable("E.T", "process temperature [K|degC]", 298.15, 0.0,1E+100,300.0,\
0,513)
DeclareVariable("E.a_H2O", "water activity (equals 1 for liquid water) [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareVariable("E.V_cell", "needed Cell-Voltage [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.V_th_0", "thermo-neutral Cell-Voltage at T=298,15K and P=1atm [V]",\
 1.481209586154748, 0.0,0.0,0.0,0,513)
DeclareVariable("E.V_rev_0", "reversible Cell-Voltage at T=298,15K and P=1atm [V]",\
 1.225486780822983, 0.0,0.0,0.0,0,513)
DeclareVariable("E.V_rev", "reversible Cell-Voltage [V]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("E.V_act", "activation overpotetial [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.V_ohm", "ohmic resistance [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.V_diff", "diffusion overpotetial [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.I", "[A]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.i", "[A/m2]", 0.0, 0.0,0.0,0.0,0,576)
DeclareVariable("E.P_el", "electrical input power [W]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.Q", "cooling power [W]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.eff", "[1]", 0.0, 0.0,1E+100,0.0,0,512)
DeclareAlias2("HS.O2_Input.m_flow", "mass flow rate of sub-component [kg/s]", \
"E.O2_Output.m_flow", -1, 5, 0, 132)
DeclareAlias2("HS.O2_Input.p", "partial pressure of sub-component [Pa|bar]", \
"E.p_O2", 1, 7, 6, 4)
DeclareAlias2("HS.H2_Input.m_flow", "mass flow rate of sub-component [kg/s]", \
"E.H2_Output.m_flow", -1, 5, 1, 132)
DeclareAlias2("HS.H2_Input.p", "partial pressure of sub-component [Pa|bar]", \
"E.p_H2", 1, 7, 5, 4)
DeclareAlias2("HS.H2O_Output.m_flow", "mass flow rate of sub-component [kg/s]", \
"E.H2O_Input.m_flow", -1, 5, 2, 132)
DeclareAlias2("HS.H2O_Output.p", "partial pressure of sub-component [Pa|bar]", \
"E.p_O2", 1, 7, 6, 4)
DeclareAlias2("HS.n_H2", "[mol/s]", "HS.der(n)", 1, 6, 1, 0)
DeclareVariable("HS.M_H2", "[kg/mol]", 2.02, 0.0,1E+100,0.0,0,513)
DeclareAlias2("HS.p_H2", "partial pressure H2 [Pa|bar]", "E.p_H2", 1, 7, 5, 0)
DeclareVariable("HS.n_O2", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("HS.M_O2", "[kg/mol]", 16, 0.0,1E+100,0.0,0,513)
DeclareAlias2("HS.p_O2", "partial pressure O2 [Pa|bar]", "E.p_O2", 1, 7, 6, 0)
DeclareVariable("HS.n_H2O", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("HS.M_H2O", "[kg/mol]", 18.02, 0.0,1E+100,0.0,0,513)
DeclareAlias2("HS.p_H2O", "partial pressure H2O [Pa|bar]", "E.p_O2", 1, 7, 6, 0)
DeclareState("HS.n", "[mol]", 1, 0, 0.0,1E+100,0.0,0,560)
DeclareDerivative("HS.der(n)", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,32), 0.0, 0);
EndEqBlock
EndDataBlock
