/* DSblock model generated by Dymola from Modelica model HydrogenComponents.Examples.ExElOnly
 Dymola Version 2018 (32-bit), 2017-04-10 translated this at Thu Apr 08 19:10:32 2021

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    2
#define NX2_   1
#define NU_    0
#define NY_    0
#define NW_    41
#define NP_    8
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 486861802
#define NHash2_ 810919187
#define NHash3_ 0
#define NI_    0
#define NRelF_ 2
#define NRel_  3
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    17
#define SizePre_ 0
#define SizeEq_ 1
#define SizeDelay_ 0
#define QNLmax_ 1
#define MAXAux 1
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 46
#define NGlobalHelpI_ 23
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0
};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0
};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="HydrogenComponents.Examples.ExElOnly";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[5]={1 , 2 , 1 , 2 , 0};
DYMOLA_STATIC int QJacobianGC_[3]={
0 , 1 , 0};
DYMOLA_STATIC double QJacobianCD_[3]={0  , 44 , 55};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,12) = 2.02;
DYNX(W_,13) = 28.9;
DYNX(W_,15) = 16;
DYNX(W_,16) = 29.8;
DYNX(W_,17) = 18.02;
DYNX(W_,22) = 298.15;
DYNX(W_,23) = 103105;
DYNX(W_,36) = 2.02;
DYNX(W_,38) = 16;
DYNX(W_,40) = 18.02;
DYNX(W_,4) = 20000.0;
DYNX(W_,19) = 236483;
DYNX(W_,21) = 2;
DYNX(W_,27) = 1.225486780822983;
DYNX(W_,24) = 1000;
DYNX(W_,18) = 1;
DYNX(W_,9) = 1.1233453792030135;
DYNX(W_,20) = 285830;
DYNX(W_,26) = 1.481209586154748;
DYNX(W_,3) = 0.00010800000000000001;
DYNX(W_,8) = 0.2;
DYNX(W_,6) = 0.1;
DYNX(W_,10) = 0.3;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(DYNhelp,0) = sqrtGuarded(9.698850686193686E-006*DYNX(DP_,6),
  "9.698850686193686E-006*E.p_O2");
DYNX(DYNhelp,1) = logGuarded(9.698850686193686E-006*DYNX(DP_,5)*DYNX(DYNhelp,0),
  "9.698850686193686E-006*(E.p_H2*sqrt(9.698850686193686E-006*E.p_O2))");
DYNX(W_,28) = 0.628786780822983+0.04308665136430147*DYNX(DYNhelp,1);
DYNX(W_,5) = 18.482391755690227*(0.005139*DYNX(DP_,3)-0.00326);
DYNX(W_,7) = (-2.04)*DYNX(DP_,4)-0.0028*sqr(DYNX(DP_,4))+5.332*DYNX(DP_,4)+
  0.2072*DYNX(DP_,4)+0.001043*powmacro2(DYNX(DP_,4),"E.m",3,"3")-0.3*sqr(
  DYNX(DP_,4));
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(F_,0) = 100;
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(F_,0) = 100;

if (Init_ || DYNTime==InitTime) {
DYNX(Aux_,0) = Less(DYNX(W_,33),"E.i", 20000.0,"20000.0", 0);}
MixedSystemOfEquations(6, DYNX(DYNhelp,2))

  { /* Non-linear system of equations to solve. */
  /* Tag: simulation.nonlinear[1] */
  /* Introducing 11 common subexpressions and reusing 1 variables totally
     used in 3 expressions */
  /* Of the common subexpressions 11 are reals, 0 are integers, and 1
     are booleans. */
  const char*const varnames_[]={"E.i"};
  const double nominal_[]={1};
  NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 1, 1, 
    DYNX(DYNhelp,8), 35, DYNX(did_->helpvari_vec,0), 23);
  SetInitVector(x__, 1, DYNX(W_,33), Remember_(DYNX(W_,33), 0));
  Residues;
    DYNX(W_,32) = DYNX(DP_,0)*DYNX(W_,33);
    DYNX(DYNhelp,43) = divmacro(1.0,"1.0",DYNX(W_,5),"E.sigma_pem");
    DYNX(W_,30) = DYNX(DYNhelp,43)*DYNX(W_,32)*DYNX(DP_,2);
    DYNX(DYNhelp,44) = Equal(DYNX(W_,33), 0, 1);
    DYNX(W_,29) = IF DYNX(DYNhelp,44) THEN 0 ELSE divmacro(8314.4598*logGuarded(
      9259.25925925926*DYNX(W_,33),"9259.25925925926*E.i"),"8314.4598*log(9259.25925925926*E.i)",
      96485.33289*DYNX(DP_,1)*2,"96485.33289*(E.alpha_m*2)");
    DYNX(W_,31) = IF DYNX(Aux_,0) THEN 0.04308665136430147*logGuarded(divmacro(
      20000.0,"20000.0",20000.0-DYNX(W_,33),"20000.0-E.i"),"20000.0/(20000.0-E.i)")
       ELSE 0;
    DYNX(W_,25) = DYNX(W_,28)+DYNX(W_,29)+DYNX(W_,30)+DYNX(W_,31);
  SetVector(residue__, 1, DYNX(X_,0)-DYNX(W_,25)*DYNX(W_,32));

  Jacobian(Jacobian__)
  MatrixZeros(Jacobian__);
  SetMatrixLeading(Jacobian__, 1, 1, 1,  -((DYNX(W_,25)+DYNX(W_,30))*DYNX(DP_,0)
    +DYNX(W_,32)*(IF DYNX(DYNhelp,44) THEN 0.0 ELSE divmacro(divmacro(
    76985738.8888889,"76985738.8888889",9259.25925925926*DYNX(W_,33),
    "9259.25925925926*E.i"),"76985738.8888889/(9259.25925925926*E.i)",
    96485.33289*DYNX(DP_,1)*2,"96485.33289*(E.alpha_m*2)"))+DYNX(W_,32)*(IF 
    DYNX(Aux_,0) THEN  -divmacro((-0.04308665136430147)*(20000.0-DYNX(W_,33)),
    "(-0.04308665136430147)*(20000.0-E.i)",sqr(20000.0-DYNX(W_,33)),
    "(20000.0-E.i)^2") ELSE 0.0)));

  SolveNonLinearSystemOfEquationsMixed(Jacobian__, residue__, x__,"Tag: simulation.nonlinear[1]");
  DYNX(W_,33) = GetVector(x__, 1);
  EndNonLinearSystemOfEquations(residue__, x__);
   /* End of Non-Linear Equation Block */ }




  MixedModeStartBoolean
  UpdateVariableNamed(DYNX(Aux_,0),"discreteexpr_0.", Less(DYNX(W_,33),"E.i", 
    20000.0,"20000.0", 0));
  MixedModeInit(1, DYNX(DYNhelp,45))
  ThetaMixedCross(0,0)
  MixedModeEndBoolean
  UpdateReal(DYNX(W_,31), 1)
  UpdateReal(DYNX(W_,30), 2)
  UpdateReal(DYNX(W_,25), 3)
  UpdateReal(DYNX(W_,29), 4)
  UpdateReal(DYNX(W_,33), 5)
  UpdateReal(DYNX(W_,32), 6)
EndMixedSystemOfEquations

DYNX(W_,11) = 5.1821347869529016E-006*DYNX(W_,32);
DYNX(W_,1) = 2.02*DYNX(W_,11);
DYNX(F_,1) = (-0.49504950495049505)*DYNX(W_,1);

AcceptedSection1

AcceptedSection2
DYNX(W_,14) = 0.5*DYNX(W_,11);
DYNX(W_,0) = 16*DYNX(W_,14);
DYNX(W_,2) = 18.02*DYNX(W_,11);
DYNX(W_,34) = 43.8*DYNX(W_,11)*(DYNX(DP_,7)-1000.0)-1.4812095861547478*
  DYNX(W_,32)+DYNX(X_,0);
DYNX(W_,35) = IF Equal(DYNX(X_,0), 0, 2) THEN 0 ELSE divmacro(285830.0*
  DYNX(W_,11),"285830.0*E.n_H2",DYNX(X_,0),"PI.Power");
DYNX(W_,37) = (-0.0625)*DYNX(W_,0);
DYNX(W_,39) = (-0.05549389567147614)*DYNX(W_,2);

DefaultSection
InitialSection
DYNX(Aux_,0) = DYNX(W_,33) < 20000.0;
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareState("PI.Power", "[W]", 0, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("PI.der(Power)", "[W/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.O2.m_flow", "mass flow rate of sub-component [kg/s]", 0.0, \
0.0,0.0,0.0,0,776)
DeclareAlias2("E.O2.p", "partial pressure of sub-component [Pa|bar]", "E.p_O2", 1,\
 7, 6, 4)
DeclareVariable("E.H2.m_flow", "mass flow rate of sub-component [kg/s]", 0.0, \
0.0,0.0,0.0,0,776)
DeclareAlias2("E.H2.p", "partial pressure of sub-component [Pa|bar]", "E.p_H2", 1,\
 7, 5, 4)
DeclareVariable("E.H2O.m_flow", "mass flow rate of sub-component [kg/s]", 0.0, \
0.0,0.0,0.0,0,776)
DeclareAlias2("E.H2O.p", "partial pressure of sub-component [Pa|bar]", "E.p_O2", 1,\
 7, 6, 4)
DeclareAlias2("E.Power", "Input power for the elektrolyser [W]", "PI.Power", 1, 1,\
 0, 0)
DeclareParameter("E.A", "active area [m2]", 0, 0.0025, 0.0,0.0,0.0,0,560)
DeclareParameter("E.alpha_m", "f\303\274r \303\234berspannung [1]", 1, 0.7353, \
0.0,0.0,0.0,0,560)
DeclareVariable("E.i_0_pem", "hat mit Material der Membran zu tun [A/m2]", \
0.00010800000000000001, 0.0,0.0,0.0,0,513)
DeclareVariable("E.i_max", "maximal stromdichte [A/m2]", 20000.0, 0.0,0.0,0.0,0,513)
DeclareParameter("E.delta_pem", "membran thickness [m]", 2, 0.00015, 0.0,0.0,0.0,\
0,560)
DeclareVariable("E.sigma_pem", "conductivity of membran [S/m]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareParameter("E.lambda", "water content of membran (dry: ~0.5; water saturated gas: ~13; liquid water: ~22)",\
 3, 22, 0.0,0.0,0.0,0,560)
DeclareVariable("E.t_max_pem", "maximale Teillast", 0.1, 0.0,0.0,0.0,0,513)
DeclareParameter("E.m", "molar Concentration of the electrolyt-solution", 4, 0.2,\
 0.0,0.0,0.0,0,560)
DeclareVariable("E.sigma_alk", "conductivity of elektrolyte [S/m]", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("E.t_max_alk", "maximale Teillast", 0.2, 0.0,0.0,0.0,0,513)
DeclareVariable("E.sigma_so", "conductivity of elektrolyte [S/m]", \
1.1233453792030135, 0.0,0.0,0.0,0,513)
DeclareVariable("E.t_max_so", "maximale Teillast", 0.3, 0.0,0.0,0.0,0,513)
DeclareVariable("E.n_H2", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.M_H2", "[kg/mol]", 2.02, 0.0,1E+100,0.0,0,513)
DeclareParameter("E.p_H2", "partial pressure H2 [Pa|bar]", 5, 400000, 0.0,1E+100,\
100000.0,0,560)
DeclareVariable("E.cp_H2", "[J/(kg.K)]", 28.9, 0.0,0.0,0.0,0,513)
DeclareVariable("E.n_O2", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.M_O2", "[kg/mol]", 16, 0.0,1E+100,0.0,0,513)
DeclareParameter("E.p_O2", "partial pressure O2 [Pa|bar]", 6, 400000, 0.0,1E+100,\
100000.0,0,560)
DeclareVariable("E.cp_O2", "[J/(kg.K)]", 29.8, 0.0,0.0,0.0,0,513)
DeclareAlias2("E.n_H2O", "[mol/s]", "E.n_H2", 1, 5, 11, 0)
DeclareVariable("E.M_H2O", "[kg/mol]", 18.02, 0.0,1E+100,0.0,0,513)
DeclareAlias2("E.p_H2O", "partial pressure H2O [Pa|bar]", "E.p_O2", 1, 7, 6, 0)
DeclareVariable("E.a_H2O", "water activity (equals 1 for liquid water) [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareVariable("E.G_r_0", "free gibbs reaktion energy at T=298,15K and P=1atm [J/mol]",\
 236483, 0.0,0.0,20000.0,0,513)
DeclareVariable("E.H_r_0", "reaktion enthalpy at T=298,15K and P=1atm [J/mol]", 285830,\
 0.0,0.0,20000.0,0,513)
DeclareVariable("E.z", "nuber of exchanged elektrons per elementary reaktion", 2,\
 0.0,0.0,0.0,0,513)
DeclareVariable("E.T_0", "standard temperature [K|degC]", 298.15, 0.0,1E+100,\
300.0,0,513)
DeclareVariable("E.p_0", "standard pressure [Pa|bar]", 103105, 0.0,0.0,0.0,0,513)
DeclareVariable("E.T", "process temperature [K|degC]", 1000, 0.0,1E+100,300.0,0,513)
DeclareParameter("E.T_u", "Umgebungstemperatur [K|degC]", 7, 293.15, 0.0,1E+100,\
300.0,0,560)
DeclareVariable("E.V_cell", "needed Cell-Voltage [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.V_th_0", "thermo-neutral Cell-Voltage at T=298,15K and P=1atm [V]",\
 1.481209586154748, 0.0,0.0,0.0,0,513)
DeclareVariable("E.V_rev_0", "reversible Cell-Voltage at T=298,15K and P=1atm [V]",\
 1.225486780822983, 0.0,0.0,0.0,0,513)
DeclareVariable("E.V_rev", "reversible Cell-Voltage [V]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("E.V_act", "activation overpotetial [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.V_ohm", "ohmic resistance [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.V_diff", "diffusion overpotetial [V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.I", "[A]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.i", "[A/m2]", 0.0, 0.0,0.0,0.0,0,576)
DeclareAlias2("E.P_el", "electrical input power [W]", "PI.Power", 1, 1, 0, 0)
DeclareVariable("E.Q", "cooling power [W]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("E.eff", "[1]", 0.0, 0.0,1E+100,0.0,0,512)
DeclareAlias2("HS.O2.m_flow", "mass flow rate of sub-component [kg/s]", \
"E.O2.m_flow", -1, 5, 0, 132)
DeclareAlias2("HS.O2.p", "partial pressure of sub-component [Pa|bar]", "E.p_O2", 1,\
 7, 6, 4)
DeclareAlias2("HS.H2.m_flow", "mass flow rate of sub-component [kg/s]", \
"E.H2.m_flow", -1, 5, 1, 132)
DeclareAlias2("HS.H2.p", "partial pressure of sub-component [Pa|bar]", "E.p_H2", 1,\
 7, 5, 4)
DeclareAlias2("HS.H2O.m_flow", "mass flow rate of sub-component [kg/s]", \
"E.H2O.m_flow", -1, 5, 2, 132)
DeclareAlias2("HS.H2O.p", "partial pressure of sub-component [Pa|bar]", "E.p_O2", 1,\
 7, 6, 4)
DeclareAlias2("HS.n_H2", "[mol/s]", "HS.der(n)", 1, 6, 1, 0)
DeclareVariable("HS.M_H2", "[kg/mol]", 2.02, 0.0,1E+100,0.0,0,513)
DeclareAlias2("HS.p_H2", "partial pressure H2 [Pa|bar]", "E.p_H2", 1, 7, 5, 0)
DeclareVariable("HS.n_O2", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("HS.M_O2", "[kg/mol]", 16, 0.0,1E+100,0.0,0,513)
DeclareAlias2("HS.p_O2", "partial pressure O2 [Pa|bar]", "E.p_O2", 1, 7, 6, 0)
DeclareVariable("HS.n_H2O", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("HS.M_H2O", "[kg/mol]", 18.02, 0.0,1E+100,0.0,0,513)
DeclareAlias2("HS.p_H2O", "partial pressure H2O [Pa|bar]", "E.p_O2", 1, 7, 6, 0)
DeclareState("HS.n", "[mol]", 1, 0, 0.0,1E+100,0.0,0,560)
DeclareDerivative("HS.der(n)", "[mol/s]", 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,33), 0.0, 0);
EndEqBlock
EndDataBlock
